//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvnConnect.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectContainer : DbContext
    {
        public ConnectContainer()
            : base("name=ConnectContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<JobTitles> JobTitles { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<ForeignLanguage> ForeignLanguages { get; set; }
        public virtual DbSet<PracticingLicense> PracticingLicenses { get; set; }
        public virtual DbSet<WorkingExperience> WorkingExperiences { get; set; }
        public virtual DbSet<ProfesstionalArea> ProfesstionalAreas { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectStaffs> ProjectStaffs { get; set; }
        public virtual DbSet<UserProjectPermission> UserProjectPermissions { get; set; }
        public virtual DbSet<ProjectActivity> ProjectActivities { get; set; }
    }
}
