//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvnConnect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectActivity
    {
        public int Id { get; set; }
        public string ProjectKey { get; set; }
        public string ByStaff { get; set; }
        public System.DateTime HappenedOn { get; set; }
        public string Message { get; set; }
    }
}
