//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvnConnect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.BindToCustomer = false;
            this.IsStared = false;
            this.IsDeleted = false;
            this.IsArchived = false;
        }
    
        public int Id { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> BindToCustomer { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string Category { get; set; }
        public string Tag { get; set; }
        public string ProjectOwner { get; set; }
        public bool IsStared { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsArchived { get; set; }
        public string ArchivedBy { get; set; }
        public Nullable<System.DateTime> ArchivedOn { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public string CompletedBy { get; set; }
    }
}
