//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvnConnect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStaffs
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string ProjectKey { get; set; }
        public string StaffKey { get; set; }
        public string AddedBy { get; set; }
        public string AddedOn { get; set; }
        public string PermissionKey { get; set; }
    }
}
