//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvnConnect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<System.DateTime> FirstDayAtWork { get; set; }
        public Nullable<System.DateTime> LastDayAtWork { get; set; }
        public string JobTitle { get; set; }
        public string Department { get; set; }
        public string Nationality { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string MaritalStatus { get; set; }
        public string IDNumber { get; set; }
        public Nullable<System.DateTime> DateOf_ID_Issue { get; set; }
        public string PlaceOf_ID_Issue { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> DateOfPassportIssue { get; set; }
        public string PlaceOfPassportIssue { get; set; }
        public string EmailAddress { get; set; }
        public string PermanentResidence { get; set; }
        public string CurrentAddress { get; set; }
        public string SocialInsuranceNumber { get; set; }
        public string PIT_Code { get; set; }
        public string PIT_Deduction { get; set; }
        public string VCBAccount { get; set; }
        public string OtherBankAccount { get; set; }
        public string OtherBankAccountSubsidiary { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactPhone { get; set; }
        public string EmergencyContactRelationship { get; set; }
        public string Key { get; set; }
        public string Avatar { get; set; }
        public System.DateTime AddedOn { get; set; }
        public string AddedBy { get; set; }
        public string ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string Password { get; set; }
    }
}
