//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvnConnect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags
    {
        public int Id { get; set; }
        public string TagKey { get; set; }
        public string TagName { get; set; }
        public string Color { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddOn { get; set; }
    }
}
