//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvnConnect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Content { get; set; }
        public string StartDate { get; set; }
        public string DueDate { get; set; }
        public string Priority { get; set; }
        public string Progress { get; set; }
        public string ETA { get; set; }
    }
}
