//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvnConnect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingExperience
    {
        public int Id { get; set; }
        public string StaffKey { get; set; }
        public string NameOfCompany { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public string CurrentlyWorking { get; set; }
        public string Jobtitle { get; set; }
        public string ResignationReason { get; set; }
    }
}
